// Generated by CoffeeScript 1.10.0
(function() {
  var Person, Student, paco, student1,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Person = (function() {
    function Person(name) {
      this.name = name;
    }

    Person.prototype.walk = function() {
      alert("I'm walking!");
    };

    Person.prototype.sayHi = function() {
      alert("Hi my name is " + this.name);
    };

    return Person;

  })();

  Student = (function(superClass) {
    extend(Student, superClass);

    function Student(name, topic) {
      this.name = name;
      this.topic = topic;
      Student.__super__.constructor.call(this, this.name);
    }

    Student.prototype.sayHi = function() {
      alert("Hi my name is " + this.name + " and i'm studying " + this.topic);
    };

    Student.prototype.sayBye = function() {
      alert("Bye!");
    };

    return Student;

  })(Person);

  paco = new Person("Paco");

  paco.sayHi();

  paco.walk();

  student1 = new Student("Carolina", "Physics");

  student1.sayHi();

  student1.walk();

  student1.sayBye();

}).call(this);
